#!/data/data/com.termux/files/usr/bin/bash
#
#
# Minimal system info fetching tool for Termux
#
# Author: Rish
# Date: June 9, 2026
# License: MIT
#
#
# Color definations
LG='\e[38;5;154m'   # Lime Green (idk what to name!?)
GC='\e[38;5;247m'   # Grey Color (kinda)
NC='\e[0m'          # No Color

if [[ $(uname -o) == "Android" ]]; then
    OS=$(uname -o)
    OS_VER=$(getprop ro.build.version.release)
    KERNEL=$(uname -r)
    DEVICE=$(getprop ro.product.manufacturer)
    MODEL=$(getprop ro.product.model)
    PKGS=$(dpkg-query -l | grep -c "^ii")
    {
        read -r _ total _
        read -r _
        read -r _ avail _
    } </proc/meminfo
    
    RAM="$(((total-avail)/1024)) / $((total/1024)) MB"
    CPU=$(getprop ro.board.platform)
    
    read khz </sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq
    mhz=$((khz/1000))
    SPEED="$((mhz/1000)).$(((mhz%1000)/10)) GHz"
    
    # this was first method i used to format the clock speed
    # SPEED="${khz:0:-6}.${khz:1:-4} GHz"
    # works only if the raw value is 7 digits
    
    UPTIME=$(uptime -p)
    DISK=$(df -h /data | awk 'NR==2 {print $3" / "$2" ("$5")"}')
    ARCH=$(uname -m)
else
    { echo "Not an Android device!"; exit 1; }
fi

main() {
    echo
    echo -e "   ${LG}OS:${NC}       ${GC}$OS $OS_VER $ARCH${NC}"
    echo -e "   ${LG}DEVICE:${NC}   ${GC}${DEVICE^} $MODEL${NC}"
    echo -e "   ${LG}KERNEL:${NC}   ${GC}${KERNEL%%-*}${NC}"
    echo -e "   ${LG}CPU:${NC}      ${GC}$CPU ($(nproc)) @ $SPEED${NC}"
    echo -e "   ${LG}SHELL:${NC}    ${GC}${SHELL##*/}${NC}"
    echo -e "   ${LG}PKGS:${NC}     ${GC}$PKGS${NC}"
    echo -e "   ${LG}DISK:${NC}     ${GC}$DISK${NC}"
    echo -e "   ${LG}RAM:${NC}      ${GC}$RAM${NC}"
    echo -e "   ${LG}UPTIME:${NC}   ${GC}${UPTIME/up }${NC}"
    echo
}
main
