#!/data/data/com.termux/files/usr/bin/bash

# Color definations
BW='\033[1;37m'     # Bold White
NC='\033[0m'        # No Color

if [[ $(uname -o) == "Android" ]]; then
    OS=$(uname -o)
    OS_VER=$(getprop ro.build.version.release)
    KERNEL=$(uname -r)
    DEVICE=$(getprop ro.product.manufacturer)
    MODEL=$(getprop ro.product.model)
    PKGS=$(dpkg-query -l | grep -c "^ii")
    {
        read -r _ total _
        read -r _
        read -r _ avail _
    } </proc/meminfo
    
    RAM="$(((total-avail)/1024)) / $((total/1024)) MB"
    CPU=$(getprop ro.board.platform)
    
    read khz </sys/devices/system/cpu/cpufreq/policy0/cpuinfo_max_freq
    mhz=$((khz/1000))
    SPEED="$((mhz/1000)).$(((mhz%1000)/10)) GHz"
    
    # this was first method i used to format the clock speed
    # SPEED="${khz:0:-6}.${khz:1:-4} GHz"
    # works only if the raw value is 7 digits
    
    UPTIME=$(uptime -p)
    DISK=$(df -h /data | awk 'NR==2 {print $3" / "$2" ("$5")"}')
    ARCH=$(uname -m)
else
    { echo "Not an Android device!"; exit 1; }
fi

main() {
    echo -e "${BW}-------------------------------------------${NC}"
    echo -e "   ${BW}OS:${NC}       $OS $OS_VER $ARCH"
    echo -e "   ${BW}DEVICE:${NC}   ${DEVICE^} $MODEL"
    echo -e "   ${BW}KERNEL:${NC}   ${KERNEL%%-*}"
    echo -e "   ${BW}CPU:${NC}      $CPU ($(nproc)) @ $SPEED"
    echo -e "   ${BW}SHELL:${NC}    ${SHELL##*/}"
    echo -e "   ${BW}PKGS:${NC}     $PKGS"
    echo -e "   ${BW}DISK:${NC}     $DISK"
    echo -e "   ${BW}RAM:${NC}      $RAM"
    echo -e "   ${BW}UPTIME:${NC}   ${UPTIME/up }"
    echo -e "${BW}-------------------------------------------${NC}"
}
main
